version: '3.9'

#NGINX
services:
  nginx:
    #builds the image from Dockerfile.nginx file in current directory
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - database
      - php
    ports:
      - 80:80 #http
      - 443:443 #https
    volumes:
      - ./wordpress:/var/www/html:delegated
#DATABASE
  database:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      # Environment variables store sensitive data
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
#PHP
  php:
    build:
      #builds the image from Dockerfile.php file in current directory
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./wordpress:/var/www/html:delegated

#WPCLI

  wp:
    build:
    # Reuses Dockerfile.php
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./wordpress:/var/www/html:delegated
    entrypoint: ["wp", "--allow-root"]
  
      